### ISSUE TITLE
doesn't appear to work on 3.3+

### ISSUE THREAD

**Issue by InnerMobius** [TayouVR/Blender_merge-bones#1]
script says it installs but nothing changes

**Comment by TayouVR** [comment]
I have just tried it again in my project and it still works.
I made this using blender 3.4.1. I am now on blender 4.2.1

it should show up in the right click menu in armature edit mode

if it doesn't idk...

I may bring this thing to extensions.blender.org though. Requires quite a bit of restructuring...

**Comment by TayouVR** [comment]
I've submitted the addon to the extensions here: https://extensions.blender.org/add-ons/org-tayou-bone-vertex-group-merge/
it is currently awaiting review.

~~EDIT: apparently you can already see the page here: https://extensions.blender.org/approval-queue/org-tayou-bone-vertex-group-merge/~~
EDIT2: it is now published at https://extensions.blender.org/add-ons/org-tayou-bone-vertex-group-merge/, you should be able to find and install it directly in blender through the "Get Extensions" menu
